### PR TITLE
Update functions.php

### PR DESCRIPTION
**Pull request by eiland-asbl**
fixed death incorrect pointing to preset blank.png.

(suggestion: allow option for PRESET image)

### CODE REVIEW

**Comment by williamsdb** [comment]
Merged this, thanks. Don't really understand your suggest for PRESET image - can you explain further please?

**Comment by eiland-asbl** [comment]
PRESET as in to define a default image instead of blank or ranfom?

**Comment by williamsdb** [comment]
I have to admit that I assumed that people would just use BLANK and replace the contents of blank.png. Do you think it is needed to have both BLANK and PRESET with a separate image file?

**Comment by eiland-asbl** [comment]
Hm, I use `post_to_bluesky` to post links to different domains. For me it would be useful to add an optional variable to this function to set a preset or to allow for the image which is being harvested from the url - instead of having to hardcode it...

**Comment by williamsdb** [comment]
So you want a different fallback image for each time you call `post_to_bluesky`?

**Comment by eiland-asbl** [comment]
not even fallback but override...

**Comment by williamsdb** [comment]
v2.0.7 just pushed now has an extra parameter in `post_to_bluesky`, $linkCardFallback, which will override the default on a post by post basis. Takes the same values as you can provide on connection: RANDOM, BLANK or ERROR.

**Pull request merged**
